SocialWall.Admin/Controllers/SourceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SocialWall.Admin.Controllers
{
    [AuthorizeUser(AccessLevel = "Admin")]
    public class SourceController : Controller
    {
        // GET: Source
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Feed(string id)
        {
            return View();
        }
    }
}

SocialWall.Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SocialWall.Admin.Controllers
{
    [AuthorizeUser(AccessLevel = "Admin")]
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Index()
        {
            return View();
        }

        // GET: User/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: User/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: User/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: User/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: User/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: User/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: User/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SocialWall.Admin/Controllers/WallController.cs
using SocialWall.Admin.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SocialWall.Admin.Controllers
{
    [AuthorizeUser(AccessLevel = "Admin")]
    public class WallController : Controller
    {
        // GET: Wall
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }
        public ActionResult Update(string id)
        {
            Wall wall = new Wall();
            wall.Id = Convert.ToInt32(id);

            return View(wall);
        }
    }
}

SocialWall.Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
 
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <link rel="icon" sizes="32x32" type="image/png" href="~/Images/favicon-32x32.png" />
    <title>@ViewBag.Title - Social Wall</title>
   
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-toggle.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />

    <script src="~/Scripts/jquery.min.js"></script>

    <script src="~/Scripts/bootstrap.min.js"></script>

      
    <script src="~/Scripts/respond.js"></script>
    
    @*@Styles.Render("~/Content/css")*@
    @*@Scripts.Render("~/bundles/modernizr")*@

    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    @*@Scripts.Render("~/bundles/jquery")*@

    <script src="~/Scripts/bootstrap-toggle.min.js"></script>
    <script src="~/Scripts/bootstrap-confirmation.min.js"></script>
    @*<script src="~/Scripts/jquery-validate.bootstrap-tooltip.js"></script>*@

    @*@Scripts.Render("~/bundles/bootstrap")*@
    @*@RenderSection("scripts", required: false)*@

    <link href="~/Scripts/smoke-v3.1.1/css/smoke.css" rel="stylesheet" />

    <script src="~/Scripts/smoke-v3.1.1/js/smoke.js"></script>

    <script>
        function GetBaseAddress() {

            return 'http://localhost:52341/';

        }
    </script>
    

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" >
        <button type="button" class="navbar-toggle" onclick="openNav()" style="float:left !important; margin-left: 15px; display:inline !important;">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        @*<div class="container">
           
            <div class="navbar-header">

                

                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                
            
                @Html.ActionLink("VOX Social Wall", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
               
              
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav" style="float: right;">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Abdul", "About", "Home")</li>
                    <li>@Html.ActionLink("LogOut", "Contact", "Home")</li>
                </ul>
            </div>
        </div>*@
        @Html.ActionLink("VOX Social Wall", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
       
       
       
        <a href="~/Account/LogOff" class="btn btn-primary" title="Log out" style="float: right;margin-right: 15px;margin-top: 7px;height: 35px;" aria-label="Left Align">
            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
        </a> 
        
        
   

    </div>


    <div id="mySidenav" class="sidenav" style="z-index: 9999;">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        @Html.ActionLink("Home", "Index", "Home")
        @Html.ActionLink("Walls", "Index", "Wall")      
        @*@Html.ActionLink("Sources", "Index", "Source")*@
        @Html.ActionLink("Users", "Index", "User")
        @*@Html.ActionLink("Settings", "Index", "Source")*@
    </div>

    <div id="main">      
       
        <div class="container-fluid body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - VOX Cinemas</p>
            </footer>
        </div>
    </div>

    <div class="loader-container">
        <div class="loader"></div>
    </div>

  

    <script>
        function openNav() {
            document.getElementById("mySidenav").style.width = "250px";
        }

        function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
        }

        function ShowLoader() {
            $('.loader-container').show();
        }

        function HideLoader() {
            $('.loader-container').hide();
        }

      
    </script>

</body>
</html>

SocialWall.Admin/Views/Shared/_LayoutAccount.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
 
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <link rel="icon" sizes="32x32" type="image/png" href="~/Images/favicon-32x32.png" />
    <title>@ViewBag.Title - Social Wall</title>
   
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-toggle.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />

    <script src="~/Scripts/jquery.min.js"></script>

    <script src="~/Scripts/bootstrap.min.js"></script>

      
    <script src="~/Scripts/respond.js"></script>
    
    @*@Styles.Render("~/Content/css")*@
    @*@Scripts.Render("~/bundles/modernizr")*@

    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    @*@Scripts.Render("~/bundles/jquery")*@

    <script src="~/Scripts/bootstrap-toggle.min.js"></script>
    <script src="~/Scripts/bootstrap-confirmation.min.js"></script>
    @*<script src="~/Scripts/jquery-validate.bootstrap-tooltip.js"></script>*@

    @*@Scripts.Render("~/bundles/bootstrap")*@
    @*@RenderSection("scripts", required: false)*@

    <link href="~/Scripts/smoke-v3.1.1/css/smoke.css" rel="stylesheet" />

    <script src="~/Scripts/smoke-v3.1.1/js/smoke.js"></script>

    <script>
        function GetBaseAddress() {

            return 'http://10.210.2.66/SocialWallAdmin/';

        }
    </script>
    

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" >
        
    
        @Html.ActionLink("VOX Social Wall", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
       
       
 
        
        
   

    </div>


    

    <div id="main">      
       
        <div class="container-fluid body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - VOX Cinemas</p>
            </footer>
        </div>
    </div>



  

    

</body>
</html>